spring:
  application:
    name: schatServer
  redis:
    host: localhost
    port: 8355
    timeout: 6000 #60sec

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /index.html #swagger path
    doc-expansion: list
    tags-sorter: alpha
    operationsSorter: method
    #groups-order: DESC
    #disable-swagger-default-url: true
    #display-request-duration: true

server:
  port: 8354

logging:
  config: classpath:log4j2/log4j2.xml
