spring:
  application:
    name: schatServer

springdoc:
  api-docs:
    enabled: true #swagger ?? ?? ??
  swagger-ui:
    path: /index.html #swagger path
    doc-expansion: list #??? ??? ?? ?? (none: ??, full: ????)
    tags-sorter: alpha # alpha(??? ????), method(HTTP????)
    operationsSorter: method #?? ? API ?? ??
    #groups-order: DESC
    #disable-swagger-default-url: true
    #display-request-duration: true

server:
  port: 8354

logging:
  config: classpath:log4j2/log4j2.xml
